language: julia
os:
  - osx
  - linux
julia:
  - release
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("JuliaResearchSnippets"); Pkg.test("JuliaResearchSnippets"; coverage=true)';
    - julia -e 'cd(Pkg.dir("JuliaResearchSnippets")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';